name: Rebuild Site

on:
  schedule:
    # - cron: '0 1 * * *' # rebuild at 01:00 every day
    - cron: '*/5 * * * *' # rebuild every 5 minutes every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: "-X POST -H 'Authorization: token ${{ secrets.PAGES_ACCESS_TOKEN }}' -H 'Accept: application/vnd.github.ant-man-preview+json' https://api.github.com/repos/tokiku-music/tokiku-music.github.io/pages/builds"