name: Rebuild Site

on:
  # schedule:
    # - cron: '0 1 * * *' # rebuild at 01:00 every day
    # - cron: '*/5 * * * *' # rebuild every 5 minutes every day
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install Jekyll
        run: |
          sudo gem install bundler jekyll
          sudo bundle install
      - name: Clean site
        run: |
          if [ -d "docs" ]; then
            rm -rf docs/*
          fi
      - name: Build site
        run: bundle exec jekyll build -d docs
      - name: Deploy build
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "Deploy with ${GITHUB_WORKFLOW}"
          git push --all -f https://${{ secrets.PAGES_ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
