name: Rebuild Site

on:
  schedule:
    # - cron: '0 1 * * *' # rebuild at 01:00 every day
    - cron: '*/5 * * * *' # rebuild every 5 minutes every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger GitHub pages rebuild
      run: |
        curl --fail --request POST \
        --url https://api.github.com/repos/tokiku-music/tokiku-music.github.io/pages/builds \
        --header "Authorization: Bearer $PAGES_ACCESS_TOKEN"

      env:
        PAGES_ACCESS_TOKEN: ${{ secrets.PAGES_ACCESS_TOKEN }}